<?php
/**
 * AccessTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kaemo\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaemo API
 *
 * Public api for Kaemo back office
 *
 * OpenAPI spec version: 1.0.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Kaemo\Client;

/**
 * AccessTest Class Doc Comment
 *
 * @category    Class */
// * @description Access
/**
 * @package     Kaemo\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccessTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Access"
     */
    public function testAccess()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "id_shop"
     */
    public function testPropertyIdShop()
    {

    }

    /**
     * Test attribute "id_customer"
     */
    public function testPropertyIdCustomer()
    {

    }

    /**
     * Test attribute "id_product"
     */
    public function testPropertyIdProduct()
    {

    }

    /**
     * Test attribute "id_product_attribute"
     */
    public function testPropertyIdProductAttribute()
    {

    }

    /**
     * Test attribute "id_order"
     */
    public function testPropertyIdOrder()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "date_add"
     */
    public function testPropertyDateAdd()
    {

    }

    /**
     * Test attribute "date_exp"
     */
    public function testPropertyDateExp()
    {

    }

    /**
     * Test attribute "cancel"
     */
    public function testPropertyCancel()
    {

    }

    /**
     * Test attribute "recurring"
     */
    public function testPropertyRecurring()
    {

    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {

    }

}
