<?php
/**
 * CommentResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kinow\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Server API
 *
 * Reference for Server API (REST/Json)
 *
 * OpenAPI spec version: 2.0.24
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Kinow\Client;

/**
 * CommentResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description CommentResponse
/**
 * @package     Kinow\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CommentResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CommentResponse"
     */
    public function testCommentResponse()
    {

    }

    /**
     * Test attribute "id_comment"
     */
    public function testPropertyIdComment()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "id_item"
     */
    public function testPropertyIdItem()
    {

    }

    /**
     * Test attribute "id_customer"
     */
    public function testPropertyIdCustomer()
    {

    }

    /**
     * Test attribute "author"
     */
    public function testPropertyAuthor()
    {

    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {

    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {

    }

    /**
     * Test attribute "date_add"
     */
    public function testPropertyDateAdd()
    {

    }

    /**
     * Test attribute "date_upd"
     */
    public function testPropertyDateUpd()
    {

    }

}
