<?php
/**
 * ConvertMediaLiveRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kinow\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Server API
 *
 * Reference for Server API (REST/Json)
 *
 * OpenAPI spec version: 2.0.27
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Kinow\Client;

/**
 * ConvertMediaLiveRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description ConvertMediaLiveRequest
/**
 * @package     Kinow\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConvertMediaLiveRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ConvertMediaLiveRequest"
     */
    public function testConvertMediaLiveRequest()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "stream_id"
     */
    public function testPropertyStreamId()
    {

    }

    /**
     * Test attribute "live_id"
     */
    public function testPropertyLiveId()
    {

    }

    /**
     * Test attribute "date_from"
     */
    public function testPropertyDateFrom()
    {

    }

    /**
     * Test attribute "date_to"
     */
    public function testPropertyDateTo()
    {

    }

}
