<?php
/**
 * CreateMessageRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kinow\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Server API
 *
 * Reference for Server API (REST/Json)
 *
 * OpenAPI spec version: 2.0.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Kinow\Client;

/**
 * CreateMessageRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description CreateMessageRequest
/**
 * @package     Kinow\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateMessageRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CreateMessageRequest"
     */
    public function testCreateMessageRequest()
    {

    }

    /**
     * Test attribute "id_lang"
     */
    public function testPropertyIdLang()
    {

    }

    /**
     * Test attribute "id_support"
     */
    public function testPropertyIdSupport()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "id_contact"
     */
    public function testPropertyIdContact()
    {

    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {

    }

    /**
     * Test attribute "id_product"
     */
    public function testPropertyIdProduct()
    {

    }

    /**
     * Test attribute "id_order"
     */
    public function testPropertyIdOrder()
    {

    }

    /**
     * Test attribute "send_mail"
     */
    public function testPropertySendMail()
    {

    }

}
