<?php
/**
 * DownloadInformationsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kaemo\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kinow API
 *
 * Client API for Kinow back-office
 *
 * OpenAPI spec version: 1.3.73
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Kaemo\Client;

/**
 * DownloadInformationsTest Class Doc Comment
 *
 * @category    Class */
// * @description DownloadInformations
/**
 * @package     Kaemo\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DownloadInformationsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "DownloadInformations"
     */
    public function testDownloadInformations()
    {

    }

    /**
     * Test attribute "source_url"
     */
    public function testPropertySourceUrl()
    {

    }

    /**
     * Test attribute "manifest"
     */
    public function testPropertyManifest()
    {

    }

    /**
     * Test attribute "session_id"
     */
    public function testPropertySessionId()
    {

    }

}
