<?php
/**
 * GoogleAnalyticsResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kinow\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Server API
 *
 * Reference for Server API (REST/Json)
 *
 * OpenAPI spec version: 2.0.22
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Kinow\Client;

/**
 * GoogleAnalyticsResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GoogleAnalyticsResponse
/**
 * @package     Kinow\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GoogleAnalyticsResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GoogleAnalyticsResponse"
     */
    public function testGoogleAnalyticsResponse()
    {

    }

    /**
     * Test attribute "analytics_id"
     */
    public function testPropertyAnalyticsId()
    {

    }

    /**
     * Test attribute "analytics_universal"
     */
    public function testPropertyAnalyticsUniversal()
    {

    }

    /**
     * Test attribute "analytics_user_id"
     */
    public function testPropertyAnalyticsUserId()
    {

    }

}
