<?php
/**
 * OrderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kaemo\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaemo API
 *
 * Public api for Kaemo back office
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Kaemo\Client;

/**
 * OrderTest Class Doc Comment
 *
 * @category    Class */
// * @description Order
/**
 * @package     Kaemo\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Order"
     */
    public function testOrder()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "id_order_renew"
     */
    public function testPropertyIdOrderRenew()
    {

    }

    /**
     * Test attribute "id_cart"
     */
    public function testPropertyIdCart()
    {

    }

    /**
     * Test attribute "id_currency"
     */
    public function testPropertyIdCurrency()
    {

    }

    /**
     * Test attribute "id_customer"
     */
    public function testPropertyIdCustomer()
    {

    }

    /**
     * Test attribute "current_state"
     */
    public function testPropertyCurrentState()
    {

    }

    /**
     * Test attribute "payment"
     */
    public function testPropertyPayment()
    {

    }

    /**
     * Test attribute "total_discounts"
     */
    public function testPropertyTotalDiscounts()
    {

    }

    /**
     * Test attribute "total_discounts_tax_incl"
     */
    public function testPropertyTotalDiscountsTaxIncl()
    {

    }

    /**
     * Test attribute "total_discounts_tax_excl"
     */
    public function testPropertyTotalDiscountsTaxExcl()
    {

    }

    /**
     * Test attribute "total_paid"
     */
    public function testPropertyTotalPaid()
    {

    }

    /**
     * Test attribute "total_paid_tax_incl"
     */
    public function testPropertyTotalPaidTaxIncl()
    {

    }

    /**
     * Test attribute "total_paid_tax_excl"
     */
    public function testPropertyTotalPaidTaxExcl()
    {

    }

    /**
     * Test attribute "total_products"
     */
    public function testPropertyTotalProducts()
    {

    }

    /**
     * Test attribute "total_products_wt"
     */
    public function testPropertyTotalProductsWt()
    {

    }

    /**
     * Test attribute "conversion_rate"
     */
    public function testPropertyConversionRate()
    {

    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {

    }

    /**
     * Test attribute "invoice_date"
     */
    public function testPropertyInvoiceDate()
    {

    }

    /**
     * Test attribute "valid"
     */
    public function testPropertyValid()
    {

    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {

    }

    /**
     * Test attribute "date_add"
     */
    public function testPropertyDateAdd()
    {

    }

    /**
     * Test attribute "date_upd"
     */
    public function testPropertyDateUpd()
    {

    }

}
