<?php
/**
 * CategoriesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Kaemo\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaemo API
 *
 * Public api for Kaemo back office
 *
 * OpenAPI spec version: 1.0.39
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Kaemo\Client;

use \Kaemo\Client\Configuration;
use \Kaemo\Client\ApiClient;
use \Kaemo\Client\ApiException;
use \Kaemo\Client\ObjectSerializer;

/**
 * CategoriesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Kaemo\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CategoriesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createCategory
     *
     * .
     *
     */
    public function testCreateCategory()
    {

    }

    /**
     * Test case for getAvailableCategories
     *
     * .
     *
     */
    public function testGetAvailableCategories()
    {

    }

    /**
     * Test case for getAvailableCategory
     *
     * .
     *
     */
    public function testGetAvailableCategory()
    {

    }

    /**
     * Test case for getCategories
     *
     * .
     *
     */
    public function testGetCategories()
    {

    }

    /**
     * Test case for getCategoriesFromCategory
     *
     * .
     *
     */
    public function testGetCategoriesFromCategory()
    {

    }

    /**
     * Test case for getCategory
     *
     * .
     *
     */
    public function testGetCategory()
    {

    }

    /**
     * Test case for getCategoryBanner
     *
     * .
     *
     */
    public function testGetCategoryBanner()
    {

    }

    /**
     * Test case for getCategoryFeatures
     *
     * .
     *
     */
    public function testGetCategoryFeatures()
    {

    }

    /**
     * Test case for getCategoryProducts
     *
     * .
     *
     */
    public function testGetCategoryProducts()
    {

    }

    /**
     * Test case for getProductCategories
     *
     * .
     *
     */
    public function testGetProductCategories()
    {

    }

    /**
     * Test case for getSubscriptionCategories
     *
     * .
     *
     */
    public function testGetSubscriptionCategories()
    {

    }

}
