<?php
/**
 * CMSCategoriesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Kinow\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kinow API
 *
 * Client API for Kinow back-office
 *
 * OpenAPI spec version: 1.4.15
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Kinow\Client;

use \Kinow\Client\Configuration;
use \Kinow\Client\ApiClient;
use \Kinow\Client\ApiException;
use \Kinow\Client\ObjectSerializer;

/**
 * CMSCategoriesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Kinow\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CMSCategoriesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createCMSCategory
     *
     * .
     *
     */
    public function testCreateCMSCategory()
    {

    }

    /**
     * Test case for getCMSCategories
     *
     * .
     *
     */
    public function testGetCMSCategories()
    {

    }

    /**
     * Test case for updateCMSCategory
     *
     * .
     *
     */
    public function testUpdateCMSCategory()
    {

    }

}
