<?php
/**
 * ImagesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Kaemo\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kinow API
 *
 * Client API for Kinow back-office
 *
 * OpenAPI spec version: 1.3.50
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Kaemo\Client;

use \Kaemo\Client\Configuration;
use \Kaemo\Client\ApiClient;
use \Kaemo\Client\ApiException;
use \Kaemo\Client\ObjectSerializer;

/**
 * ImagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Kaemo\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ImagesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for deleteProductScreenshot
     *
     * .
     *
     */
    public function testDeleteProductScreenshot()
    {

    }

    /**
     * Test case for getActorCoverImage
     *
     * .
     *
     */
    public function testGetActorCoverImage()
    {

    }

    /**
     * Test case for getCategoryBanner
     *
     * .
     *
     */
    public function testGetCategoryBanner()
    {

    }

    /**
     * Test case for getDirectorCoverImage
     *
     * .
     *
     */
    public function testGetDirectorCoverImage()
    {

    }

    /**
     * Test case for getIntroImage
     *
     * .
     *
     */
    public function testGetIntroImage()
    {

    }

    /**
     * Test case for getProductCoverImage
     *
     * .
     *
     */
    public function testGetProductCoverImage()
    {

    }

    /**
     * Test case for getProductImages
     *
     * .
     *
     */
    public function testGetProductImages()
    {

    }

    /**
     * Test case for getProductScreenshots
     *
     * .
     *
     */
    public function testGetProductScreenshots()
    {

    }

    /**
     * Test case for getSubscriptionCoverImage
     *
     * .
     *
     */
    public function testGetSubscriptionCoverImage()
    {

    }

    /**
     * Test case for getVideoCover
     *
     * .
     *
     */
    public function testGetVideoCover()
    {

    }

    /**
     * Test case for uploadActorCover
     *
     * .
     *
     */
    public function testUploadActorCover()
    {

    }

    /**
     * Test case for uploadCategoryBanner
     *
     * .
     *
     */
    public function testUploadCategoryBanner()
    {

    }

    /**
     * Test case for uploadDirectorCover
     *
     * .
     *
     */
    public function testUploadDirectorCover()
    {

    }

    /**
     * Test case for uploadProductCover
     *
     * .
     *
     */
    public function testUploadProductCover()
    {

    }

    /**
     * Test case for uploadProductScreenshot
     *
     * .
     *
     */
    public function testUploadProductScreenshot()
    {

    }

    /**
     * Test case for uploadProductScreenshots
     *
     * .
     *
     */
    public function testUploadProductScreenshots()
    {

    }

    /**
     * Test case for uploadSubscriptionCover
     *
     * .
     *
     */
    public function testUploadSubscriptionCover()
    {

    }

}
